-- Create Friendships Table (Idempotent-ish, assuming explicit run)
create table if not exists friendships (
  id bigint generated by default as identity primary key,
  user_id_1 uuid references profiles(id) not null,
  user_id_2 uuid references profiles(id) not null,
  status text check (status in ('pending', 'accepted')) not null default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id_1, user_id_2)
);

-- Index for faster lookups
create index if not exists friendships_user_id_1_idx on friendships(user_id_1);
create index if not exists friendships_user_id_2_idx on friendships(user_id_2);

-- Enable RLS
alter table friendships enable row level security;

-- Drop existing policies to recreate them safely
drop policy if exists "Users can view their own friendships" on friendships;
drop policy if exists "Users can insert friend requests" on friendships;
drop policy if exists "Users can update their friendships" on friendships;
drop policy if exists "Users can delete their friendships" on friendships;

-- Policies
-- Assumption: profiles.id IS the auth.uid(). 
-- If not, these policies need a lookup, but user specified auth_id is unused.

-- 1. Read: Users can see their own friendships
create policy "Users can view their own friendships" on friendships
  for select using (
    auth.uid() = user_id_1 or auth.uid() = user_id_2
  );

-- 2. Insert: Authenticated users can create friend requests (must be the sender)
create policy "Users can insert friend requests" on friendships
  for insert with check (
    auth.uid() = user_id_1
  );

-- 3. Update: Users can update status (accept requests where they are user_id_2)
create policy "Users can update their friendships" on friendships
  for update using (
    auth.uid() = user_id_2 or auth.uid() = user_id_1
  );
  
-- 4. Delete: Users can delete their friendships
create policy "Users can delete their friendships" on friendships
  for delete using (
    auth.uid() = user_id_1 or auth.uid() = user_id_2
  );
