
-- RE-RUN THIS SCRIPT IN SUPABASE SQL EDITOR TO RESET AND UPDATE SCHEMA

-- 1. Clean up old tables if they exist
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user();
drop table if exists matches;
drop table if exists profiles;

-- 2. Create Profiles (Decoupled from Auth)
create table profiles (
  id uuid default gen_random_uuid() primary key,
  auth_id uuid references auth.users, -- Nullable! Links to real user if they login
  username text not null unique,
  avatar_url text,
  elo integer default 1200,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Matches
create table matches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Players
  team1_p1 uuid references profiles(id) not null,
  team1_p2 uuid references profiles(id) not null,
  team2_p1 uuid references profiles(id) not null,
  team2_p2 uuid references profiles(id) not null,
  
  -- Score
  score jsonb not null, 
  winner_team smallint not null
);

-- 4. Enable Security (RLS)
alter table profiles enable row level security;
alter table matches enable row level security;

-- Policies: Allow public read/write for now to facilitate the "Group of Friends" mode
-- (In a real app, you'd restrict 'insert' to authenticated users, but allow them to create 'ghost' profiles)
create policy "Public profiles access" on profiles for select using (true);
create policy "Public profiles insert" on profiles for insert with check (true);
create policy "Public matches access" on matches for select using (true);
create policy "Public matches insert" on matches for insert with check (true);

-- 5. Auto-Link Trigger (Optional but good)
-- If a user Signs Up, we can try to link them to an existing profile by username, or create a new one.
-- For simplicity, we will just create a new profile for them if they sign up.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (auth_id, username, elo)
  values (new.id, new.raw_user_meta_data->>'username', 1200);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
