drop extension if exists "pg_net";


  create table "public"."achievements" (
    "id" text not null,
    "name" text not null,
    "description" text not null,
    "icon" text not null,
    "point_value" integer default 10
      );


alter table "public"."achievements" enable row level security;


  create table "public"."activity_logs" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "actor_id" uuid,
    "action" text not null,
    "target_id" text,
    "details" jsonb
      );


alter table "public"."activity_logs" enable row level security;


  create table "public"."clubs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "name" text not null,
    "location" text
      );


alter table "public"."clubs" enable row level security;


  create table "public"."friendships" (
    "id" bigint generated by default as identity not null,
    "user_id_1" uuid not null,
    "user_id_2" uuid not null,
    "status" text not null default 'pending'::text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."friendships" enable row level security;


  create table "public"."matches" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "team1_p1" uuid not null,
    "team1_p2" uuid not null,
    "team2_p1" uuid not null,
    "team2_p2" uuid not null,
    "score" jsonb not null,
    "winner_team" smallint not null,
    "commentary" text,
    "status" text default 'pending'::text,
    "auto_confirm_at" timestamp with time zone default (now() + '24:00:00'::interval),
    "elo_snapshot" jsonb,
    "created_by" uuid,
    "club_id" bigint
      );


alter table "public"."matches" enable row level security;


  create table "public"."messages" (
    "id" uuid not null default gen_random_uuid(),
    "content" text not null,
    "sender_id" uuid not null default auth.uid(),
    "receiver_id" uuid not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "is_read" boolean default false
      );


alter table "public"."messages" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null default gen_random_uuid(),
    "username" text not null,
    "avatar_url" text,
    "elo" integer default 1150,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "is_admin" boolean default false,
    "approved" boolean default false,
    "notifications_enabled" boolean default true,
    "subscription_end_date" timestamp with time zone default (now() + '30 days'::interval),
    "banned" boolean default false,
    "email" text,
    "banned_until" timestamp with time zone,
    "member_id" bigint generated by default as identity not null,
    "matches_validated" integer default 0,
    "matches_rejected" integer default 0,
    "main_club_id" bigint
      );


alter table "public"."profiles" enable row level security;


  create table "public"."user_achievements" (
    "user_id" uuid not null,
    "achievement_id" text not null,
    "unlocked_at" timestamp with time zone not null default timezone('utc'::text, now())
      );


alter table "public"."user_achievements" enable row level security;

CREATE UNIQUE INDEX achievements_pkey ON public.achievements USING btree (id);

CREATE UNIQUE INDEX activity_logs_pkey ON public.activity_logs USING btree (id);

CREATE UNIQUE INDEX clubs_name_key ON public.clubs USING btree (name);

CREATE UNIQUE INDEX clubs_pkey ON public.clubs USING btree (id);

CREATE UNIQUE INDEX friendships_pkey ON public.friendships USING btree (id);

CREATE INDEX friendships_user_id_1_idx ON public.friendships USING btree (user_id_1);

CREATE UNIQUE INDEX friendships_user_id_1_user_id_2_key ON public.friendships USING btree (user_id_1, user_id_2);

CREATE INDEX friendships_user_id_2_idx ON public.friendships USING btree (user_id_2);

CREATE INDEX idx_profiles_member_id ON public.profiles USING btree (member_id);

CREATE UNIQUE INDEX matches_pkey ON public.matches USING btree (id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX user_achievements_pkey ON public.user_achievements USING btree (user_id, achievement_id);

alter table "public"."achievements" add constraint "achievements_pkey" PRIMARY KEY using index "achievements_pkey";

alter table "public"."activity_logs" add constraint "activity_logs_pkey" PRIMARY KEY using index "activity_logs_pkey";

alter table "public"."clubs" add constraint "clubs_pkey" PRIMARY KEY using index "clubs_pkey";

alter table "public"."friendships" add constraint "friendships_pkey" PRIMARY KEY using index "friendships_pkey";

alter table "public"."matches" add constraint "matches_pkey" PRIMARY KEY using index "matches_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."user_achievements" add constraint "user_achievements_pkey" PRIMARY KEY using index "user_achievements_pkey";

alter table "public"."activity_logs" add constraint "activity_logs_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."activity_logs" validate constraint "activity_logs_actor_id_fkey";

alter table "public"."clubs" add constraint "clubs_name_key" UNIQUE using index "clubs_name_key";

alter table "public"."friendships" add constraint "friendships_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'accepted'::text]))) not valid;

alter table "public"."friendships" validate constraint "friendships_status_check";

alter table "public"."friendships" add constraint "friendships_user_id_1_fkey" FOREIGN KEY (user_id_1) REFERENCES public.profiles(id) not valid;

alter table "public"."friendships" validate constraint "friendships_user_id_1_fkey";

alter table "public"."friendships" add constraint "friendships_user_id_1_user_id_2_key" UNIQUE using index "friendships_user_id_1_user_id_2_key";

alter table "public"."friendships" add constraint "friendships_user_id_2_fkey" FOREIGN KEY (user_id_2) REFERENCES public.profiles(id) not valid;

alter table "public"."friendships" validate constraint "friendships_user_id_2_fkey";

alter table "public"."matches" add constraint "matches_club_id_fkey" FOREIGN KEY (club_id) REFERENCES public.clubs(id) not valid;

alter table "public"."matches" validate constraint "matches_club_id_fkey";

alter table "public"."matches" add constraint "matches_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."matches" validate constraint "matches_created_by_fkey";

alter table "public"."matches" add constraint "matches_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'rejected'::text]))) not valid;

alter table "public"."matches" validate constraint "matches_status_check";

alter table "public"."matches" add constraint "matches_team1_p1_fkey" FOREIGN KEY (team1_p1) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."matches" validate constraint "matches_team1_p1_fkey";

alter table "public"."matches" add constraint "matches_team1_p2_fkey" FOREIGN KEY (team1_p2) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."matches" validate constraint "matches_team1_p2_fkey";

alter table "public"."matches" add constraint "matches_team2_p1_fkey" FOREIGN KEY (team2_p1) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."matches" validate constraint "matches_team2_p1_fkey";

alter table "public"."matches" add constraint "matches_team2_p2_fkey" FOREIGN KEY (team2_p2) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."matches" validate constraint "matches_team2_p2_fkey";

alter table "public"."messages" add constraint "messages_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES public.profiles(id) not valid;

alter table "public"."messages" validate constraint "messages_receiver_id_fkey";

alter table "public"."messages" add constraint "messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES public.profiles(id) not valid;

alter table "public"."messages" validate constraint "messages_sender_id_fkey";

alter table "public"."profiles" add constraint "profiles_main_club_id_fkey" FOREIGN KEY (main_club_id) REFERENCES public.clubs(id) not valid;

alter table "public"."profiles" validate constraint "profiles_main_club_id_fkey";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."user_achievements" add constraint "user_achievements_achievement_id_fkey" FOREIGN KEY (achievement_id) REFERENCES public.achievements(id) not valid;

alter table "public"."user_achievements" validate constraint "user_achievements_achievement_id_fkey";

alter table "public"."user_achievements" add constraint "user_achievements_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."user_achievements" validate constraint "user_achievements_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.are_friends(u1 uuid, u2 uuid)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.friendships
    where status = 'accepted'
    and (
      (user_id_1 = u1 and user_id_2 = u2) or
      (user_id_1 = u2 and user_id_2 = u1)
    )
  );
$function$
;

CREATE OR REPLACE FUNCTION public.check_is_admin()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- Check if the current user (auth.uid()) exists in profiles with is_admin = true
  RETURN EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid() 
    AND is_admin = true
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.confirm_match(match_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  m record;
  snap jsonb;
  confirmator_id uuid;
BEGIN
  -- Get match data
  SELECT * INTO m FROM public.matches WHERE id = match_id;
  
  -- Validation
  IF m.status != 'pending' THEN
    RAISE EXCEPTION 'Match is not pending.';
  END IF;

  snap := m.elo_snapshot;
  confirmator_id := auth.uid();

  -- Update Players ELO from the snapshot
  -- Snapshot format expected: { "t1p1": 1200, "t1p2": 1150, ... } (Calculated NEW ELOs)
  
  -- Team 1
  UPDATE public.profiles SET elo = (snap->>'t1p1')::int WHERE id = m.team1_p1;
  UPDATE public.profiles SET elo = (snap->>'t1p2')::int WHERE id = m.team1_p2;
  
  -- Team 2
  UPDATE public.profiles SET elo = (snap->>'t2p1')::int WHERE id = m.team2_p1;
  UPDATE public.profiles SET elo = (snap->>'t2p2')::int WHERE id = m.team2_p2;

  -- Mark as Confirmed
  UPDATE public.matches SET status = 'confirmed' WHERE id = match_id;

  -- Increment Validation Counter for the user confirming
  -- Note: If triggered by system (auto-confirm), auth.uid() might be null or system user.
  -- We only increment if a real user is performing the action.
  IF confirmator_id IS NOT NULL THEN
      UPDATE public.profiles 
      SET matches_validated = matches_validated + 1 
      WHERE id = confirmator_id;
  END IF;

END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profiles (id, username, email, approved)
  VALUES (new.id, new.raw_user_meta_data->>'username', new.email, false);
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.process_expired_matches()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  m record;
BEGIN
  -- Find all pending matches that have passed their auto_confirm_at time
  FOR m IN SELECT id FROM public.matches WHERE status = 'pending' AND auto_confirm_at < now() LOOP
    PERFORM public.confirm_match(m.id);
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.reject_match(match_id bigint, reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  m record;
  snap jsonb;
  admin_id uuid;
  rejector_id uuid;
BEGIN
  -- Get match data
  SELECT * INTO m FROM public.matches WHERE id = match_id;
  
  -- Validation
  IF m.status != 'pending' THEN
    RAISE EXCEPTION 'Match is not pending.';
  END IF;

  snap := m.elo_snapshot;
  rejector_id := auth.uid();

  -- 1. Log to activity_logs
  INSERT INTO public.activity_logs (actor_id, action, target_id, details)
  VALUES (
    rejector_id, 
    'MATCH_REJECT', 
    match_id::text, 
    jsonb_build_object(
      'reason', reason,
      'match_snapshot', row_to_json(m)
    )
  );

  -- 2. Increment Rejection Counter for the user performing the action
  UPDATE public.profiles 
  SET matches_rejected = matches_rejected + 1 
  WHERE id = rejector_id;

  -- 3. Notify Admin (Internal Message)
  -- Find the first admin (or a specific system admin)
  SELECT id INTO admin_id FROM public.profiles WHERE is_admin = true LIMIT 1;
  
  IF admin_id IS NOT NULL THEN
    INSERT INTO public.messages (content, sender_id, receiver_id)
    VALUES (
      'Match #' || match_id || ' was rejected by user. Reason: ' || reason, 
      rejector_id, -- Sender is the user rejecting
      admin_id
    );
  END IF;

  -- 4. Perform a hard delete of the match
  DELETE FROM public.matches WHERE id = match_id;
END;
$function$
;

grant delete on table "public"."achievements" to "anon";

grant insert on table "public"."achievements" to "anon";

grant references on table "public"."achievements" to "anon";

grant select on table "public"."achievements" to "anon";

grant trigger on table "public"."achievements" to "anon";

grant truncate on table "public"."achievements" to "anon";

grant update on table "public"."achievements" to "anon";

grant delete on table "public"."achievements" to "authenticated";

grant insert on table "public"."achievements" to "authenticated";

grant references on table "public"."achievements" to "authenticated";

grant select on table "public"."achievements" to "authenticated";

grant trigger on table "public"."achievements" to "authenticated";

grant truncate on table "public"."achievements" to "authenticated";

grant update on table "public"."achievements" to "authenticated";

grant delete on table "public"."achievements" to "service_role";

grant insert on table "public"."achievements" to "service_role";

grant references on table "public"."achievements" to "service_role";

grant select on table "public"."achievements" to "service_role";

grant trigger on table "public"."achievements" to "service_role";

grant truncate on table "public"."achievements" to "service_role";

grant update on table "public"."achievements" to "service_role";

grant delete on table "public"."activity_logs" to "anon";

grant insert on table "public"."activity_logs" to "anon";

grant references on table "public"."activity_logs" to "anon";

grant select on table "public"."activity_logs" to "anon";

grant trigger on table "public"."activity_logs" to "anon";

grant truncate on table "public"."activity_logs" to "anon";

grant update on table "public"."activity_logs" to "anon";

grant delete on table "public"."activity_logs" to "authenticated";

grant insert on table "public"."activity_logs" to "authenticated";

grant references on table "public"."activity_logs" to "authenticated";

grant select on table "public"."activity_logs" to "authenticated";

grant trigger on table "public"."activity_logs" to "authenticated";

grant truncate on table "public"."activity_logs" to "authenticated";

grant update on table "public"."activity_logs" to "authenticated";

grant delete on table "public"."activity_logs" to "service_role";

grant insert on table "public"."activity_logs" to "service_role";

grant references on table "public"."activity_logs" to "service_role";

grant select on table "public"."activity_logs" to "service_role";

grant trigger on table "public"."activity_logs" to "service_role";

grant truncate on table "public"."activity_logs" to "service_role";

grant update on table "public"."activity_logs" to "service_role";

grant delete on table "public"."clubs" to "anon";

grant insert on table "public"."clubs" to "anon";

grant references on table "public"."clubs" to "anon";

grant select on table "public"."clubs" to "anon";

grant trigger on table "public"."clubs" to "anon";

grant truncate on table "public"."clubs" to "anon";

grant update on table "public"."clubs" to "anon";

grant delete on table "public"."clubs" to "authenticated";

grant insert on table "public"."clubs" to "authenticated";

grant references on table "public"."clubs" to "authenticated";

grant select on table "public"."clubs" to "authenticated";

grant trigger on table "public"."clubs" to "authenticated";

grant truncate on table "public"."clubs" to "authenticated";

grant update on table "public"."clubs" to "authenticated";

grant delete on table "public"."clubs" to "service_role";

grant insert on table "public"."clubs" to "service_role";

grant references on table "public"."clubs" to "service_role";

grant select on table "public"."clubs" to "service_role";

grant trigger on table "public"."clubs" to "service_role";

grant truncate on table "public"."clubs" to "service_role";

grant update on table "public"."clubs" to "service_role";

grant delete on table "public"."friendships" to "anon";

grant insert on table "public"."friendships" to "anon";

grant references on table "public"."friendships" to "anon";

grant select on table "public"."friendships" to "anon";

grant trigger on table "public"."friendships" to "anon";

grant truncate on table "public"."friendships" to "anon";

grant update on table "public"."friendships" to "anon";

grant delete on table "public"."friendships" to "authenticated";

grant insert on table "public"."friendships" to "authenticated";

grant references on table "public"."friendships" to "authenticated";

grant select on table "public"."friendships" to "authenticated";

grant trigger on table "public"."friendships" to "authenticated";

grant truncate on table "public"."friendships" to "authenticated";

grant update on table "public"."friendships" to "authenticated";

grant delete on table "public"."friendships" to "service_role";

grant insert on table "public"."friendships" to "service_role";

grant references on table "public"."friendships" to "service_role";

grant select on table "public"."friendships" to "service_role";

grant trigger on table "public"."friendships" to "service_role";

grant truncate on table "public"."friendships" to "service_role";

grant update on table "public"."friendships" to "service_role";

grant delete on table "public"."matches" to "anon";

grant insert on table "public"."matches" to "anon";

grant references on table "public"."matches" to "anon";

grant select on table "public"."matches" to "anon";

grant trigger on table "public"."matches" to "anon";

grant truncate on table "public"."matches" to "anon";

grant update on table "public"."matches" to "anon";

grant delete on table "public"."matches" to "authenticated";

grant insert on table "public"."matches" to "authenticated";

grant references on table "public"."matches" to "authenticated";

grant select on table "public"."matches" to "authenticated";

grant trigger on table "public"."matches" to "authenticated";

grant truncate on table "public"."matches" to "authenticated";

grant update on table "public"."matches" to "authenticated";

grant delete on table "public"."matches" to "service_role";

grant insert on table "public"."matches" to "service_role";

grant references on table "public"."matches" to "service_role";

grant select on table "public"."matches" to "service_role";

grant trigger on table "public"."matches" to "service_role";

grant truncate on table "public"."matches" to "service_role";

grant update on table "public"."matches" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."user_achievements" to "anon";

grant insert on table "public"."user_achievements" to "anon";

grant references on table "public"."user_achievements" to "anon";

grant select on table "public"."user_achievements" to "anon";

grant trigger on table "public"."user_achievements" to "anon";

grant truncate on table "public"."user_achievements" to "anon";

grant update on table "public"."user_achievements" to "anon";

grant delete on table "public"."user_achievements" to "authenticated";

grant insert on table "public"."user_achievements" to "authenticated";

grant references on table "public"."user_achievements" to "authenticated";

grant select on table "public"."user_achievements" to "authenticated";

grant trigger on table "public"."user_achievements" to "authenticated";

grant truncate on table "public"."user_achievements" to "authenticated";

grant update on table "public"."user_achievements" to "authenticated";

grant delete on table "public"."user_achievements" to "service_role";

grant insert on table "public"."user_achievements" to "service_role";

grant references on table "public"."user_achievements" to "service_role";

grant select on table "public"."user_achievements" to "service_role";

grant trigger on table "public"."user_achievements" to "service_role";

grant truncate on table "public"."user_achievements" to "service_role";

grant update on table "public"."user_achievements" to "service_role";


  create policy "Public achievements access"
  on "public"."achievements"
  as permissive
  for select
  to public
using (true);



  create policy "Admins view all logs"
  on "public"."activity_logs"
  as permissive
  for select
  to public
using ((auth.uid() IN ( SELECT profiles.id
   FROM public.profiles
  WHERE (profiles.is_admin = true))));



  create policy "Users insert own logs"
  on "public"."activity_logs"
  as permissive
  for insert
  to public
with check ((auth.uid() = actor_id));



  create policy "Admins can manage clubs"
  on "public"."clubs"
  as permissive
  for all
  to public
using ((auth.uid() IN ( SELECT profiles.id
   FROM public.profiles
  WHERE (profiles.is_admin = true))));



  create policy "Clubs are viewable by everyone"
  on "public"."clubs"
  as permissive
  for select
  to public
using (true);



  create policy "Users can delete their friendships"
  on "public"."friendships"
  as permissive
  for delete
  to public
using (((auth.uid() = user_id_1) OR (auth.uid() = user_id_2)));



  create policy "Users can insert friend requests"
  on "public"."friendships"
  as permissive
  for insert
  to public
with check ((auth.uid() = user_id_1));



  create policy "Users can update their friendships"
  on "public"."friendships"
  as permissive
  for update
  to public
using (((auth.uid() = user_id_2) OR (auth.uid() = user_id_1)));



  create policy "Users can view their own friendships"
  on "public"."friendships"
  as permissive
  for select
  to public
using (((auth.uid() = user_id_1) OR (auth.uid() = user_id_2)));



  create policy "Public matches access"
  on "public"."matches"
  as permissive
  for select
  to public
using (true);



  create policy "Public matches delete"
  on "public"."matches"
  as permissive
  for delete
  to public
using (true);



  create policy "Public matches insert"
  on "public"."matches"
  as permissive
  for insert
  to public
with check (true);



  create policy "Authenticated users can insert messages"
  on "public"."messages"
  as permissive
  for insert
  to public
with check ((auth.uid() = sender_id));



  create policy "Receivers can update entries to mark as read"
  on "public"."messages"
  as permissive
  for update
  to public
using ((auth.uid() = receiver_id))
with check ((auth.uid() = receiver_id));



  create policy "Users can view their own messages"
  on "public"."messages"
  as permissive
  for select
  to public
using (((auth.uid() = sender_id) OR (auth.uid() = receiver_id)));



  create policy "Admins can delete users"
  on "public"."profiles"
  as permissive
  for delete
  to public
using (public.check_is_admin());



  create policy "Admins can update anyone"
  on "public"."profiles"
  as permissive
  for update
  to public
using (public.check_is_admin());



  create policy "Enable read access for authenticated users"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Public profiles access"
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Public profiles delete"
  on "public"."profiles"
  as permissive
  for delete
  to public
using (true);



  create policy "Public profiles insert"
  on "public"."profiles"
  as permissive
  for insert
  to public
with check (true);



  create policy "Users can update own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = id));



  create policy "Admins can manage all user_achievements"
  on "public"."user_achievements"
  as permissive
  for all
  to public
using ((auth.uid() IN ( SELECT profiles.id
   FROM public.profiles
  WHERE (profiles.is_admin = true))));



  create policy "Public user_achievements access"
  on "public"."user_achievements"
  as permissive
  for select
  to public
using (true);



  create policy "Public user_achievements insert"
  on "public"."user_achievements"
  as permissive
  for insert
  to public
with check (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "Give users authenticated access to folder 1oj01fe_0"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'avatars'::text) AND (auth.role() = 'authenticated'::text)));



