-- 1. Create table to track notification history and prevent spam
CREATE TABLE IF NOT EXISTS public.notification_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  notification_type TEXT NOT NULL, -- 'smart_nudge', 'match_invite', etc.
  sent_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_notification_history_user_date ON public.notification_history(user_id, sent_at);

-- 2. Create the Smart Target Function
CREATE OR REPLACE FUNCTION get_reminder_targets(
  check_day_of_week INT -- 0=Sunday, 1=Monday, ..., 6=Saturday
)
RETURNS TABLE (
  user_id UUID
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- We want users who:
  -- 1. Have played on this day of the week in the last 4 weeks at least twice (habitual).
  -- 2. Have NOT played a match today (UTC).
  -- 3. Have NOT received a 'smart_nudge' in the last 20 hours.
  
  RETURN QUERY
  WITH recent_matches AS (
    -- Get matches from the last 28 days created by users
    SELECT 
      m.created_by,
      EXTRACT(DOW FROM m.created_at) as dow,
      COUNT(*) as match_count
    FROM matches m
    WHERE m.created_at > (NOW() - INTERVAL '28 days')
      AND m.created_by IS NOT NULL
    GROUP BY m.created_by, EXTRACT(DOW FROM m.created_at)
  ),
  habitual_players AS (
    -- Filter for those who play on the requested day at least twice
    SELECT rm.created_by as uid
    FROM recent_matches rm
    WHERE rm.dow = check_day_of_week
      AND rm.match_count >= 2
  ),
  played_today AS (
    -- Users who ALREADY created a match today
    SELECT m.created_by as uid
    FROM matches m
    WHERE m.created_at > CURRENT_DATE::timestamp
      AND m.created_by IS NOT NULL
  ),
  recently_notified AS (
    -- Users who got a nudge recently
    SELECT nh.user_id as uid
    FROM notification_history nh
    WHERE nh.notification_type = 'smart_nudge'
      AND nh.sent_at > (NOW() - INTERVAL '20 hours')
  )
  SELECT hp.uid 
  FROM habitual_players hp
  WHERE hp.uid NOT IN (SELECT uid FROM played_today)
    AND hp.uid NOT IN (SELECT uid FROM recently_notified);

END;
$$;
