create table if not exists public.push_subscriptions (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    subscription jsonb not null,
    user_agent text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(user_id, subscription)
);

alter table public.push_subscriptions enable row level security;

create policy "Users can insert their own subscriptions"
    on public.push_subscriptions for insert
    with check (auth.uid() = user_id);

create policy "Users can view their own subscriptions"
    on public.push_subscriptions for select
    using (auth.uid() = user_id);

create policy "Users can delete their own subscriptions"
    on public.push_subscriptions for delete
    using (auth.uid() = user_id);

-- Grants
grant all on table public.push_subscriptions to authenticated;
grant all on table public.push_subscriptions to service_role;
